version: "3.8"
services:
  mongo:
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    container_name: scream-db
    restart: always
    volumes:
      - scream-db-vol:/data/db
    ports:
      - ${DB_PORT}:27017
  app:
    build: .
    container_name: scream-api
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
volumes:
  scream-db-vol:
    external: false
