version: "3.8"
services:
  app:
    build: .
    container_name: scream-api
    restart: always
    environment:
      DB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      MONGO_URI: ${MONGO_URI}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    container_name: scream-db
    restart: always
    volumes:
      - scream-db-vol:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - ${DB_PORT}:27017
volumes:
  scream-db-vol:
    external: false
