export const BLANK_SPACES = /\s+/g;
export const DOUBLE_BLANK_SPACES = / {2}/;
export const INVALID_CHARS = /[".]/g;
export const PARENTHESES = /\(.+\)/g;
export const BREAK_LINE = /[\n]/g;
export const TEXT_TOGETHER = /([a-z])([A-Z])/g;
export const NEW_LINE_AND_TAB = /[\n\t]/g;
export const DATE_FORMAT = /\b\w+\s\d{1,2},\s\d{4}\b/;
export const QUOTES = /\s*"([^"]*)"\s*/g;
